kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tst-app-admin
rules:
- apiGroups: ["extensions", "apps", "spv.no"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tst-app-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tst-app-admin
subjects:
- kind: User
  name: <object id of User>
  namespace: tst-app

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tst-app-rolebinding
  namespace: tst-app
subjects:
- kind: User
  namespace: tst-app
  name: <object id of User>
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
